# Vectors, Matrices, Linear Algebra

In [64]:
from sympy.interactive.printing import init_printing
from sympy import *
import numpy as np 
init_printing(use_unicode=True)


## Objectives:
* Manipulate vectors and matrices
* Solve some linear algebra problems 

## 1.1 Vectors

In [65]:
u = np.array([-1, 2, 3])
v = np.array([1, 2 , 3])
print(u+v)

[0 4 6]


In [66]:
print(u-v)

[-2  0  0]


* Element wise product between two vectors

In [67]:
# elements wise product 
u*v

array([-1,  4,  9])

* dot product

In [68]:
# dot products
np.dot(u,v)

12

* cross product

In [69]:
np.cross(u, v)

array([ 0,  6, -4])

## 1.2 Matrices

In [70]:
M = Matrix([[1,2],[3,4]])
M

⎡1  2⎤
⎢    ⎥
⎣3  4⎦

In [71]:
i, j = symbols('i, j') 

def f(i, j):
    return i**2+j**2

M1 = Matrix(2, 4, f)
M1

⎡0  1  4  9 ⎤
⎢           ⎥
⎣1  2  5  10⎦

In [72]:
print('Cols and Rows of M1 matrix are {} and {}'.format(M1.cols, M1.rows))
print('the second element of row 0 is {}'.format(M1[0, 2]))

Cols and Rows of M1 matrix are 4 and 2
the second element of row 0 is 4


In [73]:
M1[2]

In [74]:
M1[:,2:4]

⎡4  9 ⎤
⎢     ⎥
⎣5  10⎦

In [75]:
a = [1, 2, 3, 4]
M2 = Matrix(2, 2, a)
M2

⎡1  2⎤
⎢    ⎥
⎣3  4⎦

* identity matrix

In [76]:
I = eye(3)
I

⎡1  0  0⎤
⎢       ⎥
⎢0  1  0⎥
⎢       ⎥
⎣0  0  1⎦

In [77]:
N = Matrix([[1, -1], [0, 2]])
N

⎡1  -1⎤
⎢     ⎥
⎣0  2 ⎦

* matrix multiplication

In [78]:
M2*N

⎡1  3⎤
⎢    ⎥
⎣3  5⎦

In [79]:
N**3

⎡1  -7⎤
⎢     ⎥
⎣0  8 ⎦

* List comprehension to create new matrix 

In [80]:
Matrix(2, 2, [i*i for i in N])

⎡1  1⎤
⎢    ⎥
⎣0  4⎦

## 1.3 Linear algebra

* transpose of a matrix

In [81]:
transpose(M2)

⎡1  3⎤
⎢    ⎥
⎣2  4⎦

In [82]:
transpose(M1)

⎡0  1 ⎤
⎢     ⎥
⎢1  2 ⎥
⎢     ⎥
⎢4  5 ⎥
⎢     ⎥
⎣9  10⎦

* rank of a matrix

In [83]:
# rank of a matrix
I.rank()

In [84]:
# determinant of a matrix
I.det()

In [85]:
M2.rank()

In [86]:
M2.det()

In [87]:
M2.inv()

⎡-2    1  ⎤
⎢         ⎥
⎣3/2  -1/2⎦

In [88]:
M2**-1

⎡-2    1  ⎤
⎢         ⎥
⎣3/2  -1/2⎦

* eigenvalues

In [89]:
evals = M2.eigenvals()
evals

In [90]:
evals.values()

dict_values([1, 1])

## 2 Exercises


### 2.1 Vector manipulation
* Q 2.1.1 - Define the two vectors
$$c = \begin{bmatrix} 
  \sin(\theta)\cos(\phi) \\
  \sin(\theta)\sin(\phi)\\
  \cos(\theta)
\end{bmatrix}
, 
o = \begin{bmatrix} 
  -\cos(\theta)\cos(\phi) \\
  -\cos(\theta)\sin(\phi)\\
  \sin(\theta)
\end{bmatrix}$$

In [91]:
t,a = symbols('t,a')


In [92]:
c = [sin(t)*cos(a),sin(t)*sin(a), cos(t)]

In [93]:
o = [-cos(t)*cos(a), -cos(t)*sin(a),sin(t)]




In [94]:

res =np.dot(o,c)
res.trigsimp()


* Q 2.1.2 - Prove that these vectors are orthogonal 

In [95]:
res =np.dot(o,c)
res.trigsimp()


* Q2.1.3 - prove that their norm is 1

In [96]:
an = sqrt(np.dot(o,o))
print(an.simplify())          

1


In [97]:

an = sqrt(np.dot(c,c))
print(an.simplify())

1


* Q2.1.3 - Compute the third vector $b$ that is orthogonal to both $o$ and $c$

In [98]:
b = np.cross(c,o)
b

array([sin(a)*sin(t)**2 + sin(a)*cos(t)**2,
       -sin(t)**2*cos(a) - cos(a)*cos(t)**2, 0], dtype=object)

### 2.2 Basic matrices computation

Consider the following matrices:
$$
A = \begin{bmatrix} 
  -3 & 2 \\
   0 & 4\\
   1 & -1
\end{bmatrix}
, 
B = \begin{bmatrix} 
  1 & 2 \\
  0 & 1 \\
  1 & 1
\end{bmatrix}
$$
* Q 2.2.1 - Find a matrix $C$ such that $A-2B-C=0$
* Q 2.2.2 - Find a matrix $D$ such that $A+B+C+4D =0$

In [99]:
A = Matrix([[-3,2], [0,4], [1, -1]])
B = Matrix([[1, 2], [0,1], [1,1]])

### 2.3 Linear system 
Find the following linear system by first using solve and then using matrix representation.

$$
  \begin{cases}
    x_1 + 2x_2 + 3x_3 + 4x_4 &= 25,\\
    -x_2 + x_3 -x_4 &= 5,\\
    x_1 + 2x_2+ 2x_3 &= 20, \\
    2x_1 + 3x_3 &= 19
  \end{cases}
$$



In [100]:
x1,x2,x3,x4 = symbols ('x1,x2,x3,x4')

In [106]:
eqn1 = Eq(x1+2*x2+3*x3+4*x4, 25)
eqn2 = Eq(-x2+x3-x4, 5)
eqn3 = Eq(x1+2*x2+2*x3, 20)
eqn4 = Eq(2*x1+3*x3, 19)

nonlinsolve([eqn1, eqn2, eqn3, eqn4], (x1, x2, x3, x4))

In [107]:
eqn1, eqn2, eqn3, eqn4

In [109]:
x = Matrix([x1, x2, x3, x4]).transpose()
A = Matrix([[1, 2, 3, 4], [0, -1, 1, -1], [1, 2, 2, 0], [2, 0, 3, 0]])
B = Matrix([25, 5, 20, 19])

A.inv()*A

⎡1  0  0  0⎤
⎢          ⎥
⎢0  1  0  0⎥
⎢          ⎥
⎢0  0  1  0⎥
⎢          ⎥
⎣0  0  0  1⎦

In [110]:
A.inv()*B

⎡ -2 ⎤
⎢    ⎥
⎢10/3⎥
⎢    ⎥
⎢23/3⎥
⎢    ⎥
⎣-2/3⎦

In [111]:
A.rank()
A.inv()

⎡-1/4    -1   -1/4    3/4 ⎤
⎢                         ⎥
⎢              11         ⎥
⎢-1/24  -1/6   ──    -5/24⎥
⎢              24         ⎥
⎢                         ⎥
⎢ 1/6   2/3    1/6   -1/6 ⎥
⎢                         ⎥
⎣5/24   -1/6  -7/24  1/24 ⎦

In [112]:
(A.transpose()*A).inv()*A.transpose()*B

⎡ -2 ⎤
⎢    ⎥
⎢10/3⎥
⎢    ⎥
⎢23/3⎥
⎢    ⎥
⎣-2/3⎦

In [113]:
A.QRdecomposition()

⎛⎡√6   4⋅√57   31⋅√3458    5⋅√91 ⎤  ⎡    2⋅√6  11⋅√6   2⋅√6  ⎤⎞
⎜⎢──   ─────   ────────    ───── ⎥  ⎢√6  ────  ─────   ────  ⎥⎟
⎜⎢6      57      3458        91  ⎥  ⎢     3      6      3    ⎥⎟
⎜⎢                               ⎥  ⎢                        ⎥⎟
⎜⎢     -√57    24⋅√3458   -4⋅√91 ⎥  ⎢    √57   5⋅√57    √57  ⎥⎟
⎜⎢0    ─────   ────────   ───────⎥  ⎢0   ───   ─────    ───  ⎥⎟
⎜⎢       19      1729        91  ⎥  ⎢     3      57      3   ⎥⎟
⎜⎢                               ⎥, ⎢                        ⎥⎟
⎜⎢√6   4⋅√57    -√3458     -√91  ⎥  ⎢          √3458  2⋅√3458⎥⎟
⎜⎢──   ─────    ───────    ───── ⎥  ⎢0    0    ─────  ───────⎥⎟
⎜⎢6      57       494        13  ⎥  ⎢            38      91  ⎥⎟
⎜⎢                               ⎥  ⎢                        ⎥⎟
⎜⎢√6  -4⋅√57   -6⋅√3458     √91  ⎥  ⎢                 24⋅√91 ⎥⎟
⎜⎢──  ───────  ─────────    ───  ⎥  ⎢0    0      0    ────── ⎥⎟
⎝⎣3      57       1729       91  ⎦  ⎣                   91   ⎦⎠

In [42]:
A = Matrix([[1, 2, 3, 4],[0, -1, 1, -1],[1, 2, 2, 0], [2, 0, 3, 0]])
A


⎡1  2   3  4 ⎤
⎢            ⎥
⎢0  -1  1  -1⎥
⎢            ⎥
⎢1  2   2  0 ⎥
⎢            ⎥
⎣2  0   3  0 ⎦

In [43]:
B = Matrix([[25], [5], [20], [19]])
B

⎡25⎤
⎢  ⎥
⎢5 ⎥
⎢  ⎥
⎢20⎥
⎢  ⎥
⎣19⎦

In [44]:
A.solve_least_squares(B)

⎡ -2 ⎤
⎢    ⎥
⎢10/3⎥
⎢    ⎥
⎢23/3⎥
⎢    ⎥
⎣-2/3⎦

In [45]:
A.QRsolve(B)

⎡ -2 ⎤
⎢    ⎥
⎢10/3⎥
⎢    ⎥
⎢23/3⎥
⎢    ⎥
⎣-2/3⎦

In [46]:
X = A.inv()*B
X

⎡ -2 ⎤
⎢    ⎥
⎢10/3⎥
⎢    ⎥
⎢23/3⎥
⎢    ⎥
⎣-2/3⎦

 2.4 Commuting matrices 
In linear algebra, two matrices $A$ and $B$ are said to commute if $A.B = B.A$ and equivalently their commutator $A.B - B.A = 0$.
Find all the matrices that when commutes with matrix 
$A = 
\begin{bmatrix}
1 & 0 & 0 \\
0 & 3 & 0 \\
0 & 0 & 5
\end{bmatrix}
$
can be writen in the form of:
$$
B = \begin{bmatrix}
k_1  & 0 & 0 \\
0 & k_2 & 0 \\
0 & 0 & k_3
\end{bmatrix} , k_1, k_2, k_3 \in \rm I\!R
$$


In [54]:
A = Matrix([[1, 0, 0], [0, 3, 0], [0, 0, 5]])
a11, a12, a13, a21, a22, a23, a31, a32, a33 = symbols('a11, a12, a13, a21, a22, a23, a31, a32, a33')
B = Matrix([[a11, a12, a13], [a21, a22, a23], [a31, a32, a33]])
A, B


⎛⎡1  0  0⎤  ⎡a₁₁  a₁₂  a₁₃⎤⎞
⎜⎢       ⎥  ⎢             ⎥⎟
⎜⎢0  3  0⎥, ⎢a₂₁  a₂₂  a₂₃⎥⎟
⎜⎢       ⎥  ⎢             ⎥⎟
⎝⎣0  0  5⎦  ⎣a₃₁  a₃₂  a₃₃⎦⎠

In [56]:
P = A*B - B*A
P

⎡  0    -2⋅a₁₂  -4⋅a₁₃⎤
⎢                     ⎥
⎢2⋅a₂₁    0     -2⋅a₂₃⎥
⎢                     ⎥
⎣4⋅a₃₁  2⋅a₃₂     0   ⎦

In [57]:
linsolve(flatten(P), (a11, a12, a13, a21, a22, a23, a31, a32, a33))

### 2.5 Invertible matrix
For which values of $t$ the following matrix is not invertible: 
$$ A = 
\begin{bmatrix}
t+3 & -1 & 1\\
5 & t-3 & 2\\
6 & -6 & t+4 \\ 
\end{bmatrix}
$$

In [47]:
t = symbols('t')
A = Matrix([[t+3, -1, 1], [5, t-3, 2], [6, -6, t+4 ]])
A.det()


In [48]:
solve(A.det(),t)

### 2.6 Pseudo inverse of matrix

The pseudo-inverse of a $m\times n$ matrix $A$ is a generalization of a inverse matrix.
For an overdetermined set of linear equations represented by its matrix $A$ (with $m \ge n$),
if A is full column rank, meaning $rank(A) = n \le m$. Therefore, $A^{T}.A$ is not singular and the pseudo-inverse $A^{\dagger}$ is a left inverse of $A$, in the sense that $A^{\dagger}.A = In$
In this case we have the closed-form expresson $A^{\dagger} = (A^{T}. A)^{-1}.A^{T}$.
The solution to the least-squares problem $min_{x} \Vert Ax-y\Vert$, where the minimum norm is $x^{\ast} = A^{\dagger}.y$

Now consider the following linear systems, find the solution using least-square method:

$$
  \begin{cases}
    x+z & = 1.5\\
    x-y & =2.1\\
    x-z & = 0.8\\
    x+y & = 0.6
  \end{cases}
$$

In [49]:
x,y,z = symbols ('x,y,z')


In [50]:
N = Matrix([[1,0,1],[1,-1,0], [1,0,-1],[1,1,0]])
M = Matrix([[1.5],[2.1],[0.8], [0.6]])

In [51]:
(N.transpose()*N).inv()*N.transpose()*M

⎡1.25 ⎤
⎢     ⎥
⎢-0.75⎥
⎢     ⎥
⎣0.35 ⎦

In [52]:
N.solve_least_squares(M)

⎡1.25 ⎤
⎢     ⎥
⎢-0.75⎥
⎢     ⎥
⎣0.35 ⎦

In [53]:
eqn1 = Eq(x+z, 1.5)
eqn2 = Eq(x-y, 2.1)
eqn3 = Eq(x-z, 0.8)
eqn4 = Eq(x+y, 0.6)
linsolve((eqn1, eqn2, eqn3, eqn4), (x, y, z))